version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: algebra_booking_db
    environment:
      POSTGRES_DB: algebra_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data